Added MUI to Admin page
Mystic-Slice/course-binder pull request #20
Opened 2023-05-08 19:47 UTC by mava123-0

2023-05-10 03:25 UTC, Mystic-Slice requested changes

2023-05-10 03:25 UTC, Mystic-Slice commented on src/Components/adminManageUser.tsx
> +                        <><span className='text-red-700'>This field is required</span><br /></>}
Please remove this line

2023-05-11 15:01 UTC, mava123-0 commented
Drop-down in admin page now shows a red outline if left unselected

2023-05-12 13:59 UTC, Mystic-Slice approved these changes
LGTM!

2023-05-12 13:59 UTC, merged